let catalog = [
  {name: "1初识vue"},
  {name: "2.14自定义过滤器"},
  {name: "2.2自定义指令"},
  {name: "3计算器属性"},
  {name: "4v-bind绑定动态class和style"},
  {name: "5.4.2 事件各种修饰符"},
  {name: "7.1.2组件的创建和使用"},
  {name: "7.3.3父链和子链"},
  {name: "7.4.1slot分发内容"},
  {name: "7.4.3单个和具名slot"},
  {name: "7.4.4作用域插槽"},
  {name: "7.4.5访问slot"},
  {name: "7.5.1递归组件"},
  {name: "7.5.2内联模板"},
  {name: "7.5.3动态组件"},
  {name: "7.6.1$nextTick和异步队列更新"},
  {name: "7.6.2x-template"},
  {name: "7.6.3手动挂载实例"},
  {name: "8.1自定义组件的v-module"},
  {name: "9.插件"}
]